add inline method calls
coppolaemilio/dialogic pull request #1022
Opened 2022-07-15 09:01 UTC by M7mdKady14

enable the inline option in the call_node event and choose a number.

use the [signal=number] and put the number that you put in the call_node to call the method

2022-07-15 10:28 UTC, Jowan-Spooner commented on addons/dialogic/Events/Call Node/event.gd
> +var Signal_Number: int = 1
I would suggest to make this a string instead.

2022-07-15 10:29 UTC, Jowan-Spooner requested changes

2022-07-15 10:48 UTC, M7mdKady14 commented on addons/dialogic/Events/Call Node/event.gd
>  	}
tbh I don't know what that even does, I just found that all variables are there and put Inline there too

2022-07-18 18:49 UTC, Jowan-Spooner commented on addons/dialogic/Events/Call Node/event.gd
>  	}
All variables have to be put there to be saved. They are saved in a shortcode format e.g.: `[call_node method="dosomething" node="MyAutoload" wait="True" signal_name="MySingnal"]`
It seems like the One_Off variable wont be actually saved.
Also try to keep the keys as self-explanatory as possible, because people who write timelines in text format will have to write these.

2022-07-18 19:58 UTC, Jowan-Spooner commented on addons/dialogic/Events/Call Node/event.gd
> +	add_body_edit('Single_Use', ValueType.Bool, 'Signle Use', '', {}, 'Inline == true')
There is a typo in the label.

2022-07-19 08:41 UTC, Jowan-Spooner approved these changes
There is a typo left in one of the edits, but I'll approve the changes because I'm not at home and don't always know when I will see the changes.

2022-07-23 12:55 UTC, merged