allow unique typing sounds per-character
coppolaemilio/dialogic pull request #689
Opened 2021-12-23 21:11 UTC by uzkbwza

Implements #364.

https://user-images.githubusercontent.com/43023911/147291487-7956bdbf-7ca6-4de7-9985-1a957f4a20aa.mp4

2022-02-22 07:13 UTC, mechPenSketch commented
I have reused my previous test scene to test this pr, deleting `addon/dialogic/` first before adding the newest one in.

When I go to Dialogic > Themes > Default Theme, the following message is printed on the output:
```
res://addons/dialogic/Example Assets/Sound Effects/Beep.wav
res://addons/dialogic/Example Assets/Sound Effects/Beep.wav
res://addons/dialogic/Example Assets/Sound Effects/Beep.wav
res://addons/dialogic/Example Assets/Sound Effects/Beep.wav
res://addons/dialogic/Example Assets/Sound Effects/Beep.wav
 Resource file not found: res://Default 6 (1).wav.
 Resource file not found: res://Default 6 (1).wav.
 scene/resources/resource_format_text.cpp:157 - Couldn't load external resource: res://Default 6 (1).wav
```

Why does it try to get `Default 6 (1).wav` when my theme isn't updated to get that file somewhere?

2022-02-22 08:17 UTC, mechPenSketch requested changes
I suggest you go to the `res://addons/dialogic/Nodes/DialogNode.tscn` scene to make one change.

There is also one print statement I'd recommend to remove.

2022-02-22 08:17 UTC, mechPenSketch commented on addons/dialogic/Editor/ThemeEditor/AudioPicker.gd
> +	print(path)
I'm not sure whether you still need this, but it's best to remove the print statement once you have no use for it so that the print statement won't get clustered in the long run.

2022-02-22 09:20 UTC, mechPenSketch commented
For now, I have an issue running the project with this PR:
![dialogic_audio2](https://user-images.githubusercontent.com/15977859/155101102-062747f8-0a3c-43af-92fe-da1bdd269368.png)
Fixing the missing 6(1).wav file would most likely resolve it, but I would test this out later.

2022-02-22 12:13 UTC, AnidemDex commented
Needs a rebase, the las commit was 2 months ago

2022-02-28 18:49 UTC, coppolaemilio commented
I'll see if I can rebase it

2022-03-09 12:25 UTC, mechPenSketch commented on addons/dialogic/Nodes/DialogNode.tscn
> +samples = [ ExtResource( 11 ) ]
Or replace it with the generic beep that other Audio Nodes uses.

2022-03-09 12:30 UTC, mechPenSketch commented
Here is the test project: [dialogic_sandbox.zip](https://github.com/coppolaemilio/dialogic/files/8214609/dialogic_sandbox.zip)

I have modified `res://addons/dialogic/Nodes/DialogNode.tscn` so that `FX/Audio/Typing`'s `Samples` contains `res://addons/dialogic/Example Assets/Sound Effects/Beep.wav` instead of `Default 6 (1).wav` and it now works fine.

2022-03-10 17:25 UTC, uzkbwza commented on addons/dialogic/Editor/ThemeEditor/AudioPicker.gd
> +	print(path)
Oops! thanks for catching that. my bad.

2022-06-18 21:02 UTC, coppolaemilio commented
Hello uzkbwza. We are currently in a feature freeze for the 1.X branch. If you want to keep working on 1.X there are still some bugs that need fixing but are not high priority; you can check the milestone: https://github.com/coppolaemilio/dialogic/milestone/7

Otherwise feel free to familiarize with our work on the 2.0 branch and feel free to contribute there.

Cheers!

2022-06-18 21:02 UTC, closed without merging